# File cấu hình chung cho dự án WPSILA
# Thông số sẽ áp dụng trên toàn bộ các file bash trong dự án
# File nào sau khi cài install_lcmp sẽ được bổ sung email của người cài
# Mục đích là để lấy cấp phát https & làm email đăng ký admin WordPress

# 1. Phiên bản PHP
PHP_VER="8.3"

# 2. Phiên bản MariaDB
MARIADB_VER="10.11"